### ISSUE TITLE
[REQUEST] RewriteCond differentiated from RewriteRule?

### ISSUE THREAD

**Issue by proimage** [mrmlnc/vscode-apache#4]
I feel like making the `RewriteCond` keyword a different color than `RewriteRule` would help differentiate between the two types of lines at a glance. I'm not sure how much of the coloring you can control through the syntax highlighter vs the color theme, but I'm imagining that giving `RewriteCond` a color that is the same as `RewriteRule`, but with half the opacity, would work well.

Here's a mockup:

![image](https://user-images.githubusercontent.com/1027523/45028861-5a60d300-b04f-11e8-973e-49a197c8a85b.png)

**Comment by mrmlnc** [comment]
Thanks for issue :tada:

Please file this issue to the [original repository](https://github.com/colinta/ApacheConf.tmLanguage). This package is an adaptation of the original repository for VS Code.
